/* eslint-disable */
// tslint:disable
/**
 * @backstage/plugin-catalog-backend
 * The Backstage backend plugin that provides the Backstage catalog
 *
 * OpenAPI spec version: 1.6.0-next.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

export * from "./api";
export * from "./models";
export * from "./configuration";
export { RequiredError } from "./runtime";
export type { FetchAPI, FetchArgs } from "./runtime";
